function dx = dyn_zero_to_t_plan(in1,udummy)
%DYN_ZERO_TO_T_PLAN
%    DX = DYN_ZERO_TO_T_PLAN(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    18-Feb-2022 21:46:20

cqi = in1(1,:);
dqi = in1(3,:);
kai = in1(4,:);
sqi = in1(2,:);
dx = [-dqi.*sqi;cqi.*dqi;kai;0.0;0.0;1.0];
