function dx = trig_dyn_zero_to_t_plan(in1,udummy)
%TRIG_DYN_ZERO_TO_T_PLAN
%    DX = TRIG_DYN_ZERO_TO_T_PLAN(IN1,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-May-2022 19:56:24

cqi = in1(1,:);
dqi = in1(3,:);
kai = in1(4,:);
sqi = in1(2,:);
dx = [-dqi.*sqi;cqi.*dqi;kai;0.0;0.0;1.0];
